# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ea37327871879a155fbdd95f4fc71822"
name = "discount-tier"
application_url = "https://tier-pricing-discount-production.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
scopes = "write_discounts,read_discounts"

[auth]
redirect_urls = [ "https://tier-pricing-discount-production.up.railway.app/api/callback" ]
