query CartInput {
  cart {
    lines {
      id
      quantity
      attribute(key: "_bundle_id") {
        value
      }
      isAddon: attribute(key: "_is_addon") {
        value
      }
      cost {
        amountPerQuantity {
          amount
        }
        subtotalAmount {
          amount
        }
      }
      merchandise {
        ... on ProductVariant {
          id
          title
          product {
            id
            patchType: metafield(namespace: "custom", key: "patch_type") {
              value
            }
            priceChart: metafield(namespace: "custom", key: "price_chart_tiers") {
              value
            }
            inAnyCollection: inCollection(id: "gid://shopify/Collection/0")
          }
        }
      }
    }
    cost {
      subtotalAmount {
        amount
      }
    }
  }
  enteredDiscountCodes {
    code
  }
  shop {
    promoCodes: metafield(namespace: "custom", key: "promo_codes") {
      value
    }
  }
}
